boostorg/mysql

include/boost/mysql/detail/auxiliar/impl/row_base.ipp

Replaced unspecified behavior for pointer comparisons
with function objects with guaranteed behavior.
Close #135

UB fix for row_base in debug builds

---

.drone.star
bench/CMakeLists.txt
cmake/test_utils.cmake
test/unit/CMakeLists.txt
tools/ci/ci_util/cmake.py
tools/ci/ci_util/main.py

All test targets (including integration tests) are now only built when the `tests` target is built.
Added a CMake build that doesn't run integration testing (verifying that BOOST_MYSQL_INTEGRATION_TESTS works)
close #261

CMake test targets are now marked EXCLUDE_FROM_ALL

---

doc/qbk/22_sql_formatting.qbk
doc/qbk/helpers/Formattable.qbk
doc/qbk/helpers/quickref.xml
example/batch_inserts_generic.cpp
include/boost/mysql/detail/format_sql.hpp
include/boost/mysql/format_sql.hpp
include/boost/mysql/impl/format_sql.hpp
include/boost/mysql/impl/format_sql.ipp
test/integration/test/snippets/sql_formatting.cpp
test/unit/CMakeLists.txt
test/unit/Jamfile
test/unit/test/format_sql/formattable_ref.cpp

format_context_base::append_value now uses formattable_ref instead of being a template
close #284

Added formattable_ref

---

include/boost/mysql/character_set.hpp
include/boost/mysql/detail/character_set.hpp
include/boost/mysql/impl/character_set.ipp
include/boost/mysql/impl/connection_impl.ipp
include/boost/mysql/impl/internal/sansio/connection_state_data.hpp
include/boost/mysql/impl/internal/sansio/set_character_set.hpp
test/common/src/printing.cpp
test/fuzzing/fuzz_utf8mb4.cpp
test/integration/test/snippets/charsets.cpp
test/unit/include/test_unit/ff_charset.hpp
test/unit/test/sansio/reset_connection.cpp
test/unit/test/sansio/run_pipeline.cpp
test/unit/test/sansio/set_character_set.cpp

character_set::name is now a const char*, since NULL characters are not allowed by MySQL
character_set::next_char doesn't need to be noexcept
Removed noexcepts from next_char functions
Internal refactor

Character set clean-up

---

test/common/include/test_common/netfun_helpers.hpp
test/common/include/test_common/netfun_maker.hpp
test/common/include/test_common/tracker_executor.hpp
test/common/src/tracker_executor.cpp
test/integration/src/async_callback.cpp
test/integration/test/any_connection.cpp
test/integration/test/reconnect.cpp
test/integration/test/spotchecks.cpp
test/unit/include/test_unit/test_stream.hpp
test/unit/src/test_stream.cpp
test/unit/test/connection_pool/connection_pool_impl.cpp
test/unit/test/detail/engine_impl.cpp

Added the ability to detect the executor call stack and whether we're running from an initiating function or not.
Integration tests now consistently check these two.

Improved tracker_executor

---

.drone.star
.github/workflows/coverage.yml
.github/workflows/fuzz.yml
test/fuzzing/Jamfile
tools/docker/build-clang17.dockerfile
tools/docker/build-clang18.dockerfile
tools/scripts/build_unix_local.sh

Updated build-clang17 and build-clang18 to use ubuntu:24.04
Fix missing package in build-clang18
Fuzzers now fail if OpenSSL can't be found
close #323

Fuzzers now run normally and are more resilient to failures

---

example/timeouts.cpp
include/boost/mysql/connection_pool.hpp
include/boost/mysql/detail/async_helpers.hpp
include/boost/mysql/detail/connection_impl.hpp
test/common/include/test_common/network_result.hpp
test/integration/test/any_connection.cpp
test/integration/test/connection_pool.cpp

All initiations have now an associated executor.
close #330

Async ops now support cancel_after and similar tokens

---

example/Jamfile
test/Jamfile
tools/ci/ci_util/b2.py

Valgrind now uses a Boost.MySQL-specific b2 feature

---

doc/qbk/21_connection_pool.qbk
include/boost/mysql/connection_pool.hpp
test/integration/test/connection_pool.cpp

Improved connection_pool docs on thread-safety.
close #370

connection_pool destructor now cancels async operations

---

include/boost/mysql/connection_pool.hpp
include/boost/mysql/pool_params.hpp

Fix defect in connection_pool docs
close #290

Document that ping_interval should be >= wait_timeout

---

example/Jamfile
example/pipeline.cpp
include/boost/mysql/impl/with_diagnostics.hpp
include/boost/mysql/with_diagnostics.hpp
test/Jamfile
test/integration/test/any_connection.cpp
test/unit/test/with_diagnostics.cpp

This makes asio::as_tuple and asio::redirect_error usable as partial completion tokens with any_connection and connection_pool.
Removed leftover comment in the pipeline example.

with_diagnostics now passes through unknown signatures

---

.github/workflows/coverage.yml
test/Jamfile

Workarounds a problem with the build-gcc13 container, which uses a non-LTS Ubuntu release and can't be installed packages

Updated the coverage build to use gcc-14

---

example/private/launch_server.py
example/private/run_batch_inserts.py
example/private/run_connection_pool.py
example/private/run_tutorial_connection_pool.py

Refactored launch_server into a common utility
launch_server now uses `Popen.terminate()`, which handles the race condition case
close #393

Fixed a race condition in Windows CI when running the example servers

---

test/Jamfile

Required because of
https://github.com/boostorg/context/issues/263

Removed the -fcf-protection gcc workaround

---

include/boost/mysql/impl/internal/connection_pool/connection_node.hpp
include/boost/mysql/impl/internal/connection_pool/connection_pool_impl.hpp
include/boost/mysql/impl/internal/connection_pool/sansio_connection_node.hpp
test/integration/test/connection_pool.cpp
test/unit/test/connection_pool/connection_pool_impl.cpp
test/unit/test/connection_pool/sansio_connection_node.cpp

Changed the algorithm that calculates how many connections to create to correctly take into account the number of pending requests.
This makes the pool resize as expected and avoids potential deadlocks.
close #395

connection_pool now resizes correctly in the presence of pending connections

---

example/Jamfile
test/unit/test/detail/typing/pos_map.cpp

test_pos_map/reset_nonempty no longer triggers an assertion

---

include/boost/mysql/detail/engine_impl.hpp
test/integration/test/any_connection.cpp
test/unit/test/detail/engine_impl.cpp

Now connection/any_connection async operations are cancelled even when the cancellation signal is emitted after an intermediate operation completes, but before its intermediate handler gets called.
Restored a connection_id integration test that required this fix.
close #199

Fixed a race condition in per-operation cancellation in connection operations

---

include/boost/mysql/impl/connection_impl.ipp
include/boost/mysql/impl/internal/sansio/connection_state_data.hpp
include/boost/mysql/impl/internal/sansio/handshake.hpp
include/boost/mysql/impl/internal/sansio/quit_connection.hpp
include/boost/mysql/impl/internal/sansio/top_level_algo.hpp
test/integration/test/snippets/prepared_statements.cpp
test/unit/CMakeLists.txt
test/unit/Jamfile
test/unit/include/test_unit/algo_test.hpp
test/unit/include/test_unit/printing.hpp
test/unit/src/utils.cpp
test/unit/test/sansio/quit_connection.cpp
test/unit/test/sansio/top_level_algo.cpp

Quit now correctly marks TLS as terminated, even if it encounters an error
Removed ssl_state

Added quit_connection unit tests and refactored

---

include/boost/mysql/impl/internal/protocol/capabilities.hpp
include/boost/mysql/impl/internal/protocol/deserialization.hpp
include/boost/mysql/impl/internal/protocol/serialization.hpp
include/boost/mysql/impl/internal/sansio/connection_state_data.hpp
include/boost/mysql/impl/internal/sansio/handshake.hpp
test/unit/include/test_unit/printing.hpp
test/unit/src/utils.cpp
test/unit/test/protocol/capabilities.cpp
test/unit/test/protocol/deserialization.cpp
test/unit/test/protocol/serialization.cpp
test/unit/test/sansio/handshake.cpp

capabilities is now a scoped enum

---

include/boost/mysql/impl/internal/protocol/static_buffer.hpp
include/boost/mysql/metadata.hpp

This fixes compilation failures we've seen in Gentoo when trying to run the boost testuite.

Add <cstdint> to fix compilation failures with gcc-15.
